language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=ounit OUNIT_CI=true PINS="ounit:. ounit-lwt:."
matrix:
  include:
    - name: "ounit: linux"
      apt:
        packages:
          - libxml2-utils
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit"

    - name: "ounit-lwt: linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit-lwt"

    - name: "ounit: reverse dependencies with linux"
      os: linux
      env: OCAML_VERSION=4.08 PACKAGE="ounit" REVDEPS="mock-ounit junit_ounit pa_ounit qcheck-ounit" POST_INSTALL_HOOK="opam install -t fileutils"

    - name: "ounit: old ocaml release with linux"
      os: linux
      env: OCAML_VERSION=4.02 PACKAGE="ounit"

    - name: "ounit: MacOSX"
      os: osx
      env: OCAML_VERSION=4.08 PACKAGE="ounit" REVDEPS="junit_ounit"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew

    - name: "ounit-lwt: MacOSX"
      os: osx
      env: OCAML_VERSION=4.08 PACKAGE="ounit-lwt"
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
